### ISSUE TITLE
Finish the exercise

### ISSUE THREAD

**Issue by nasivuela** [Adalab/f-m1-evaluacion-intermedia-libertadpozos#1]
Really cool job @libertadpozos !!!

Here you have some tips to improve the exercise:

- [x] Fix the meta title of the page, something like 'Adalab Digital' may do the trick
- [x] Menu items should be clickable
- [x] Remove `alt` attribute from links.
- [x] Improve hierarchy adding more common styles to `body` tag as font-size, font-family, font-weight, color, background-color
- [x] Main title should be vertically and horizontally centered (should we use Flex to achieve this?)
- [x] Finish the main title styles: words should jump and the typography isRubik bolder
- [x] Remove commented CSS rules
- [x] Organize your files in folders, you have a guide to help you with that here --> https://books.adalab.es/materiales-front-end-f/modulo-1.-hola-mundo/1_1_intro_a_la_web#notas-finales-sobre-como-organizar-nuestro-proyecto

Once you have these fixed do the tablet styles

Let me know if you have any doubts ;)

Go for it!!

**Comment by libertadpozos** [comment]
Thanks! 
I'll do it. 
See you later :)

**Comment by libertadpozos** [comment]
Hey @nasivuela !

Here is the exercise finished. Well, unless I think so, lol. I hope you can check it out. 
Thanks in advance :)

**Comment by nasivuela** [comment]
Well done @libertadpozos !

I have unchecked a point that still needs some work. To center the title vertically, you need to make the height of the main area grow `100vh`.

Also here you have more improvements:

- [ ] Indent your code to improve readability and avoid bugs.
- [ ] Add the URL of GitHub pages to the main page, next to the description, so everybody can see it.
- [ ] On media queries you don't need to repeat properties hat already exists on the mobile version. Just add the new ones or the ones you need to modify.
- [ ] Main title still needs some work, it should be bigger on the tablet, and 'Diversidad' word is slightly moved to the right (maybe because of the width?)

**Comment by libertadpozos** [comment]
Hey, @nasivuela I've done the improvements. Can you check it, please?
Thanks! :)

**Comment by nasivuela** [comment]
Super @libertadpozos, you got it!

![](https://media.giphy.com/media/Dg0hzaN9wiEjS/giphy.gif)
